version: '3.4'

services:
  dockerproject:
    image: ${DOCKER_REGISTRY-}dockerproject
    build:
      context: .
      dockerfile: DockerProject\Dockerfile
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'

